-- Farm Code system migration
-- Adds farms, farm_codes, farm_members tables for multi-user role-based access

-- Farms table (one per owner)
CREATE TABLE IF NOT EXISTS farms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    owner_id INT NOT NULL,
    farm_code VARCHAR(20) UNIQUE NOT NULL,
    location VARCHAR(255),
    description TEXT,
    is_active TINYINT(1) DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_farm_code (farm_code),
    INDEX idx_farm_owner (owner_id)
) ENGINE=InnoDB;

-- Farm invite codes (generated by owners, used by workers to join)
CREATE TABLE IF NOT EXISTS farm_codes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    farm_id INT NOT NULL,
    code VARCHAR(20) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'field_worker',
    max_uses INT DEFAULT 1,
    current_uses INT DEFAULT 0,
    expires_at DATETIME NULL,
    is_active TINYINT(1) DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (farm_id) REFERENCES farms(id) ON DELETE CASCADE,
    INDEX idx_code (code),
    INDEX idx_code_active (code, is_active)
) ENGINE=InnoDB;

-- Farm members (links users to farms with specific roles)
CREATE TABLE IF NOT EXISTS farm_members (
    id INT AUTO_INCREMENT PRIMARY KEY,
    farm_id INT NOT NULL,
    user_id INT NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'field_worker',
    status VARCHAR(20) DEFAULT 'active',
    joined_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    approved_by INT NULL,
    FOREIGN KEY (farm_id) REFERENCES farms(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE KEY unique_farm_user (farm_id, user_id),
    INDEX idx_member_farm (farm_id),
    INDEX idx_member_user (user_id)
) ENGINE=InnoDB;

-- Activity log for farm operations
CREATE TABLE IF NOT EXISTS activity_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    farm_id INT NULL,
    user_id INT NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(50),
    entity_id INT,
    details TEXT,
    ip_address VARCHAR(45),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_activity_farm (farm_id),
    INDEX idx_activity_user (user_id),
    INDEX idx_activity_date (created_at)
) ENGINE=InnoDB;

-- Pending join requests (workers who entered a code but await approval)
CREATE TABLE IF NOT EXISTS farm_join_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    farm_id INT NOT NULL,
    user_id INT NOT NULL,
    code_used VARCHAR(20) NOT NULL,
    requested_role VARCHAR(50) NOT NULL,
    status VARCHAR(20) DEFAULT 'pending',
    reviewed_by INT NULL,
    reviewed_at DATETIME NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (farm_id) REFERENCES farms(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_request_farm (farm_id),
    INDEX idx_request_status (farm_id, status)
) ENGINE=InnoDB;
