"use client";
import * as React from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Eye, Printer, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { INVOICE_TEMPLATES, generateInvoiceHtml, generateQuoteHtml, generateReceiptHtml, type FarmProfile } from "@/components/invoices/InvoiceTemplates";
/**
 * TemplateGallery — FlowCV-style visual preview of every document design.
 *
 * Instead of picking from name + description cards, the farmer sees a real,
 * miniature render of each template (generated by the same engine that prints
 * the final document), browses them per document type, and can open any
 * template full-size or print it — all with the farm's own branding baked in.
 */

export type DocType = "invoice" | "receipt" | "quote";

const DOC_TYPES: { id: DocType; label: string }[] = [
  { id: "invoice", label: "Invoices" },
  { id: "receipt", label: "Receipts" },
  { id: "quote", label: "Quotes" },
];

/** Sample data shaped exactly like the print pages pass it. */
function sampleDoc(type: DocType) {
  const base = {
    id: 0,
    invoiceNumber: "INV-202609-0001",
    quoteNumber: "QTE-202609-0001",
    items: [
      { description: "Grade A eggs (tray of 30)", qty: 20, unitPrice: 450 },
      { description: "Fresh milk (20L can)", qty: 3, unitPrice: 1100 },
      { description: "Broiler chicken, dressed (kg)", qty: 12, unitPrice: 520 },
    ],
    totalAmount: 20740,
    amountPaid: 8000,
    paymentStatus: "partial",
    createdAt: new Date().toISOString(),
    dueDate: new Date(Date.now() + 14 * 864e5).toISOString(),
    validUntil: new Date(Date.now() + 14 * 864e5).toISOString(),
    notes: "Thank you for supporting local farming!",
    customer: { name: "Jane Wanjiru", phone: "+254 711 222 333" },
    sale: { id: 1 },
  };
  return base;
}

function renderDoc(type: DocType, templateId: string, profile: FarmProfile): string {
  const doc = sampleDoc(type);
  if (type === "quote") return generateQuoteHtml(doc, templateId, profile);
  if (type === "receipt") return generateReceiptHtml(doc, templateId, profile);
  return generateInvoiceHtml(doc, templateId, profile);
}

/** Shrink a full print document into a tappable thumbnail. */
function MiniPreview({ html, onClick }: { html: string; onClick: () => void }) {
  const ref = React.useRef<HTMLDivElement>(null);

  React.useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const iframe = document.createElement("iframe");
    iframe.setAttribute("sandbox", "allow-same-origin");
    iframe.style.cssText = "width:794px;height:1123px;border:0;pointer-events:none;transform-origin:0 0;position:absolute;top:0;left:0;";
    iframe.setAttribute("aria-hidden", "true");
    el.appendChild(iframe);
    const doc = iframe.contentDocument;
    if (doc) {
      doc.open();
      doc.write(html);
      doc.close();
    }
    return () => { iframe.remove(); };
  }, [html]);

  return (
    <button onClick={onClick} className="group relative block w-full overflow-hidden rounded-xl border border-[#E5E7EB] bg-white transition hover:border-[#166534] hover:shadow-lg focus:outline-none focus:ring-2 focus:ring-[#166534]/40" style={{ aspectRatio: "210/297" }} aria-label="Open full template preview">
      <div ref={ref} className="relative h-full w-full overflow-hidden">
        {/* iframe is scaled to thumbnail width by CSS below */}
        <style>{`.tpl-scale{transform:scale(var(--s,0.34));}`}</style>
        <ScaleFixer containerRef={ref} />
      </div>
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/10 to-transparent opacity-0 transition group-hover:opacity-100" />
      <div className="pointer-events-none absolute inset-0 flex items-center justify-center opacity-0 transition group-hover:opacity-100">
        <span className="flex items-center gap-1.5 rounded-full bg-[#166534] px-3 py-1.5 text-xs font-semibold text-white shadow-lg"><Eye className="h-3.5 w-3.5" /> Preview</span>
      </div>
    </button>
  );
}

/** Applies the scale transform once the container has a real width. */
function ScaleFixer({ containerRef }: { containerRef: React.RefObject<HTMLDivElement | null> }) {
  React.useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const apply = () => {
      const frame = el.querySelector("iframe") as HTMLIFrameElement | null;
      if (!frame) return;
      const scale = el.clientWidth / 794;
      frame.style.transform = `scale(${scale})`;
      frame.style.height = `${1123}px`;
      // let the parent clip
    };
    apply();
    const ro = new ResizeObserver(apply);
    ro.observe(el);
    return () => ro.disconnect();
  }, [containerRef]);
  return null;
}

export function TemplateGallery({ profile, currentSelection, onSelect }: { profile: FarmProfile; currentSelection: Record<DocType, string>; onSelect?: (type: DocType, templateId: string) => void }) {
  const [docType, setDocType] = React.useState<DocType>("invoice");
  const [fullPreview, setFullPreview] = React.useState<{ type: DocType; templateId: string } | null>(null);
  const [htmlCache, setHtmlCache] = React.useState<Record<string, string>>({});

  // Pre-render mini HTML for every template for the active doc type
  React.useEffect(() => {
    const next: Record<string, string> = {};
    for (const t of INVOICE_TEMPLATES) next[t.id] = renderDoc(docType, t.id, profile);
    setHtmlCache(next);
  }, [docType, profile]);

  const openFull = (t: { id: string }) => setFullPreview({ type: docType, templateId: t.id });

  const printFull = () => {
    if (!fullPreview) return;
    const html = renderDoc(fullPreview.type, fullPreview.templateId, profile);
    const w = window.open("", "_blank", "width=800,height=900");
    if (!w) return;
    w.document.write(html);
    w.document.close();
  };

  const useThisTemplate = () => {
    if (!fullPreview || !onSelect) return;
    onSelect(fullPreview.type, fullPreview.templateId);
  };

  const inUseForPreview = fullPreview ? currentSelection?.[fullPreview.type] === fullPreview.templateId : false;

  return (
    <div>
      {/* Doc type tabs */}
      <div className="mb-4 flex flex-wrap gap-2">
        {DOC_TYPES.map((d) => (
          <button key={d.id} onClick={() => setDocType(d.id)}
            className={`rounded-full border px-4 py-1.5 text-xs font-semibold transition ${docType === d.id ? "bg-[#166534] text-white border-[#166534]" : "bg-white text-[#64748B] border-[#E5E7EB] hover:border-[#BBF7D0]"}`}>
            {d.label}
          </button>
        ))}
        <span className="ml-auto self-center text-[11px] text-[#94A3B8]">Shown with your branding — click any design to open it full-size</span>
      </div>

      {/* Gallery grid */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
        {INVOICE_TEMPLATES.map((t, i) => (
          <motion.div key={t.id} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.04 }}>
            <div className="relative">
              <MiniPreview html={htmlCache[t.id] || ""} onClick={() => openFull(t)} />
              <div className="mt-2 flex items-center justify-between gap-1">
                <div className="min-w-0">
                  <p className="truncate text-xs font-bold text-[#0F172A]">{t.name}</p>
                  <p className="truncate text-[10px] text-[#94A3B8]">{t.description}</p>
                </div>
                {currentSelection?.[docType] === t.id ? (
                  <span className="shrink-0 rounded-full bg-[#F0FDF4] px-2 py-0.5 text-[9px] font-bold uppercase text-[#166534]">In use</span>
                ) : onSelect ? (
                  <button onClick={(e) => { e.stopPropagation(); onSelect(docType, t.id); }}
                    className="shrink-0 rounded-full bg-[#F1F5E8] px-2 py-0.5 text-[9px] font-bold uppercase text-[#166534] hover:bg-[#166534] hover:text-white transition">Use</button>
                ) : null}
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Full-size preview modal */}
      <AnimatePresence>
        {fullPreview && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-2 sm:p-6"
            onClick={() => setFullPreview(null)}>
            <motion.div initial={{ scale: 0.95, y: 10 }} animate={{ scale: 1, y: 0 }}
              className="flex max-h-[95vh] w-full max-w-3xl flex-col rounded-2xl bg-white"
              onClick={(e) => e.stopPropagation()}>
              <div className="flex items-center justify-between border-b border-[#E5E7EB] px-5 py-3">
                <div>
                  <h3 className="text-sm font-bold text-[#0F172A]">
                    {INVOICE_TEMPLATES.find((t) => t.id === fullPreview.templateId)?.name}
                    <span className="ml-2 text-xs font-medium text-[#94A3B8] capitalize">· {fullPreview.type} preview</span>
                  </h3>
                  <p className="text-[11px] text-[#94A3B8]">Rendered live with your logo, colors and details</p>
                </div>
                <div className="flex items-center gap-2">
                  {onSelect && fullPreview.type !== "invoice" && (
                    <Button size="sm" variant="outline" onClick={() => setDocType(fullPreview.type)}
                      className="hidden sm:inline-flex gap-1.5 rounded-lg text-[11px]">Switch to {DOC_TYPES.find((d) => d.id === fullPreview.type)?.label} tab to set</Button>
                  )}
                  {onSelect && (
                    <Button size="sm" onClick={useThisTemplate} disabled={inUseForPreview}
                      className={`gap-1.5 rounded-lg ${inUseForPreview ? "bg-[#F0FDF4] text-[#166534] border border-[#BBF7D0]" : "bg-[#166534] hover:bg-[#14532d]"}`}>
                      {inUseForPreview ? <><Check className="h-3.5 w-3.5" /> In use</> : <><Check className="h-3.5 w-3.5" /> Use for {fullPreview.type}s</>}
                    </Button>
                  )}
                  <Button size="sm" variant="outline" onClick={printFull} className="gap-1.5 rounded-lg"><Printer className="h-3.5 w-3.5" /> Test print</Button>
                  <button onClick={() => setFullPreview(null)} className="rounded-lg p-1.5 hover:bg-slate-100"><X className="h-5 w-5 text-slate-500" /></button>
                </div>
              </div>
              <div className="flex-1 overflow-y-auto bg-[#F1F5F9] p-4">
                <FullDocFrame html={renderDoc(fullPreview.type, fullPreview.templateId, profile)} />
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

/** Full-size, scrollable render inside the modal. */
function FullDocFrame({ html }: { html: string }) {
  const ref = React.useRef<HTMLDivElement>(null);
  React.useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const iframe = document.createElement("iframe");
    iframe.setAttribute("sandbox", "allow-same-origin");
    iframe.style.cssText = "width:794px;height:1123px;border:0;";
    el.appendChild(iframe);
    const doc = iframe.contentDocument;
    if (doc) { doc.open(); doc.write(html); doc.close(); }
    return () => { iframe.remove(); };
  }, [html]);
  return <div ref={ref} className="mx-auto w-[794px] max-w-full shadow-xl" style={{ transform: "scale(1)" }} />;
}
